# -*- coding: utf-8 -*-
"""Copy of Simple_maze.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FuBmnvbcCDtl1W0dRcKROfp8CX8zGTet
"""

import imp
import numpy as np
import time
import copy

from EnvSim import *

# run a simulation
grid_world = Grid_world(map_num=10)
goal_trajectory = grid_world.get_goal_trajectory()
goal_locations = grid_world.get_locations(goal_trajectory, as_list=True)
obstacle_locations = grid_world.get_locations(-1, as_list=True)
LTL_formula = ('&', ('^', (None, 'g')), ('#', ('~', (None, 'o'))) )
predicates = {
    'g':goal_locations,
    'o':obstacle_locations
}
print(grid_world.map)
model = build_model(grid_world.shape)
state_history, action_history, reward, better_policy = run_episode(grid_world, model, LTL_formula, predicates, n_steps=8)

action_history, better_policy, reward

N, W, Q, P = {}, {}, {}, {}
run_simulation((5,5), n_goals= 1, ordered_goals=False, n_episodes=1, C=1, tow=0.1, n_steps=10, n_samples=500, N=N, W=W, Q=Q, P=P)
